/**
 * GET /api/runs/[id]/artifact/[kind] — auth-gated artifact download.
 *
 * Re-checks ownership on every hit, then proxies the GCS object. We
 * never hand out raw `gs://` URIs or signed URLs at MVP — that would
 * tie the browser to GCP and bypass our auth layer. When we move to
 * Cloud Run + real GCS, this route stays the same and just streams
 * from a private bucket via ADC.
 *
 * Local dev: streams from fake-gcs-server via STORAGE_EMULATOR_HOST.
 */
import { NextResponse } from "next/server";

import { auth } from "@/auth";
import { prisma } from "@/lib/db";
import { openObject } from "@/lib/storage";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const FILE_EXT: Record<string, string> = {
  package_md: "md",
  package_json: "json",
  package_pdf: "pdf",
  diagram_svg: "svg",
  diagram_png: "png",
  prompt_log: "json",
  source_snapshot: "json",
};

export async function GET(
  _req: Request,
  ctx: { params: Promise<{ id: string; kind: string }> },
): Promise<Response> {
  const { id, kind } = await ctx.params;

  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "unauthenticated" }, { status: 401 });
  }

  // Single query: ownership + the artifact row. Avoids a second round-trip.
  const run = await prisma.run.findUnique({
    where: { id },
    select: {
      userId: true,
      artifacts: {
        // Cast: ArtifactKind enum is generated by Prisma; the route param
        // is an arbitrary string and may not match. Filter then check.
        where: { kind: kind as never },
        select: { gcsUri: true, mime: true },
        take: 1,
      },
    },
  });

  if (!run) return NextResponse.json({ error: "not_found" }, { status: 404 });
  if (run.userId !== session.user.id) {
    return NextResponse.json({ error: "forbidden" }, { status: 403 });
  }
  const artifact = run.artifacts[0];
  if (!artifact) return NextResponse.json({ error: "no_such_artifact" }, { status: 404 });

  let object;
  try {
    object = await openObject(artifact.gcsUri);
  } catch (err) {
    console.error("[artifact] openObject failed", { id, kind, err });
    return NextResponse.json({ error: "storage_error" }, { status: 502 });
  }

  const ext = FILE_EXT[kind] ?? "bin";
  const filename = `tessar-${id}.${ext}`;
  const headers = new Headers({
    "content-type": object.contentType || artifact.mime || "application/octet-stream",
    // `attachment` triggers the browser's download dialog; the run page
    // hands the same URL to <a download> so the filename is honored.
    "content-disposition": `attachment; filename="${filename}"`,
    "cache-control": "private, no-store",
  });
  if (object.contentLength != null) {
    headers.set("content-length", String(object.contentLength));
  }

  return new Response(object.stream, { status: 200, headers });
}
